'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4927
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Simple_Suduko_Solver.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0\deflang1033{\fonttbl{\f0\fnil\fcharset0 Calibri;}{\f1\fnil\fcharset1 Siyam Rupali;}{\f2\fnil\fcharset0 Siyam Rupali;}{\f3\fnil Siyam Rupali;}{\f4\fnil\fcharset2 Symbol;}}
        '''{\colortbl ;\red155\green0\blue211;\red79\green129\blue189;\red102\green102\blue102;}
        '''{\*\generator Msftedit 5.41.21.2509;}\viewkind4\uc1\pard\sa200\sl240\slmult1\cf1\lang9\ul\f0\fs48 Sudoku Solver\fs36\par
        '''\cf0\lang2117\ulnone\f1\fs20\u2447?\u2439? \u2488?\u2475?\u2463?\u2451?\u2527?\u2494?\u2480? \u2470?\ [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Sudoku_Help() As String
            Get
                Return ResourceManager.GetString("Sudoku_Help", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0\deflang1033{\fonttbl{\f0\fnil\fcharset0 Calibri;}{\f1\fnil\fcharset0 Siyam Rupali;}{\f2\fnil\fcharset1 Siyam Rupali;}}
        '''{\colortbl ;\red0\green77\blue187;\red100\green107\blue134;\red102\green102\blue102;\red79\green129\blue189;}
        '''{\*\generator Msftedit 5.41.21.2509;}\viewkind4\uc1\pard\sa200\sl276\slmult1\cf1\lang9\ul\f0\fs48 Sudoku Solver \cf2\fs32 Tips\par
        '''\cf3\lang1033\ulnone\f1\fs24 How to solve and unsolved sudoku\par
        '''\cf0\lang2117\f2\fs20\u2472?\u2495?\u2458?\u2503?\u2 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Tips() As String
            Get
                Return ResourceManager.GetString("Tips", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
